apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kadhemhafsi/tpachatproject:97
        ports:
        - containerPort: 8089
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "tpachato"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: ""  # Aucun mot de passe pour MySQL
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/SpringMVC"
        - name: SERVER_PORT
          value: "8089"
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: ClusterIP  # Service accessible uniquement au sein du cluster
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
